name: spawn-vm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "h1_h1_passthrough"
      TEST_ROOT: "tests"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Workflow Artifacts
      run: |
        echo "starting ls"
        ls
        echo "end ls"
        echo $GITHUB_WORKSPACE
        echo "pwd"
        pwd
        echo "before cd"
        cd $GITHUB_WORKSPACE
        mkdir worflow-artifacts
        echo "after cd creating dir"
        ls
        echo "final"
        echo "echo Installing World... " >> install-world.sh 
        ls
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create VM
      run: |
        az provider register -n Microsoft.VirtualMachineImages
    - name: Build and Distribute Custom VM Image      
      uses: azure/build-vm-image@v0
      with:        
        resource-group-name: '${{ secrets.CLUSTER_RESOURCE_GROUP }}'
        location: 'eastus2'
        managed-identity: 'myImageBuilderIdentity'
        source-os-type: 'linux'
        source-image-type: 'PlatformImage'
        source-image: Canonical:UbuntuServer:18.04-LTS:latest 
        customizer-source: ${{ GITHUB.WORKSPACE }}/workflow-artifacts
        customizer-script: |
          sudo mkdir /buildArtifacts
          sudo cp -r /tmp/ /buildArtifacts/
          sh /buildArtifacts/workflow-artifacts/install-world.sh