name: Spawn cluster

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: Trigger h1_h1_passthrough
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: anuruddhal
        repo: ballerina-performance
        github_token: ${{ secrets.BALLERINA_BOT_TOKEN }}
        workflow_file_name: h1_h1_passthrough.yml
        ref: master
        wait_interval: 300
        inputs: '{}'
        trigger_workflow: true
        wait_workflow: true
