name: test_h1_h1_passthrough

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ test_h1_h1_passthrough ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "h1_h1_passthrough"
      PAYLOAD_SIZE: "1024"
      TEST_ROOT: "tests"
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create VM Instance
      id: vminstance
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az vm create --resource-group "${{ secrets.CLUSTER_RESOURCE_GROUP }}"  --name "test-bal-perf-vm-${{ GITHUB.RUN_NUMBER }}"  --admin-username "${{ secrets.VM_USER }}" --admin-password "${{ secrets.VM_PWD }}" --location  eastus \
          --image "mi_1623913725906"
          echo "::set-output name=ip-address::$(az vm show -d -g "${{ secrets.CLUSTER_RESOURCE_GROUP }}" -n "test-bal-perf-vm-${{ GITHUB.RUN_NUMBER }}" --query publicIps -o tsv)"
    - name: Test output
      run: |
        echo ${{ steps.vminstance.outputs.ip-address }}
        echo "${{ steps.vminstance.outputs.ip-address }}"
#    - name: Undeploy Kubernetes artifacts
#      run: |
#        kubectl delete -f ${TEST_ROOT}/${TEST_NAME}/final.yaml
