name: Build main branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action@master
      env:
        CI_BUILD: true
        WORKING_DIR: "./bal/h1_h1_passthrough"
      with:
        args:
          build
    - name: Docker push
      run: docker push anuruddhal/h1_h1_passthrough:latest
    - name: Copy artifacts
      run: |
        ls -ltr
        cp -a ./bal/h1_h1_passthrough/target/kubernetes/h1_h1_passthrough/. ./base/h1_h1_passthrough/
    - name: 'Install Kustomize'
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - name: 'Run Kustomize'
      run: |
          pwd
          ls -ltr ./base/h1_h1_passthrough
          kustomize build base > ./gitops/base.yaml
    - name: Configure AKS
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
    - name: Deploy artifacts
      run: |
        kubectl apply --recursive -f ./gitops/base.yaml
