name: Build main branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action@master
      env:
        CI_BUILD: true
      with:
        args:
          build ./bal/h1_h1_passthrough
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker push
      run: docker push anuruddhal/h1_h1_passthrough:v1
    - name: Deploy Kubernetes
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    - run: |
        kubectl apply --recursive -f ./bal/h1_h1_passthrough/target/kubernetes

