name: Build main branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change Dir
      run:  cd bal/h1_h1_passthrough
    - name: Ballerina Build
      uses: ballerina-platform/ballerina-action@master
      env:
        CI_BUILD: true
      with:
        args:
          build
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        tags: anuruddhal/h1_h1_passthrough:v1
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
